name: Daily Sync Trigger

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Trigger sync endpoint
        run: |
          curl -X GET \
            -H "x-api-key: ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.API_BASE_URL }}/trigger/sync
